In [41]:
import pandas as pd
import numpy as np

In [42]:
df=pd.read_csv("C:\\Users\\HARSHITA\\Downloads\\Churn_Modelling - Churn_Modelling.csv")
df.head(3)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

In [43]:
categorical_col=df.select_dtypes(include=['object'])
categorical_col

        Surname Geography  Gender
0      Hargrave    France  Female
1          Hill     Spain  Female
2          Onio    France  Female
3          Boni    France  Female
4      Mitchell     Spain  Female
...         ...       ...     ...
9995   Obijiaku    France    Male
9996  Johnstone    France    Male
9997        Liu    France  Female
9998  Sabbatini   Germany    Male
9999     Walker    France  Female

[10000 rows x 3 columns]

In [44]:
numerical_col=df.select_dtypes(exclude=['object'])
numerical_col

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

In [45]:
df.drop(columns=['Surname','Geography'],inplace=True)

In [46]:
df['Gender']=df['Gender'].map({'Female':1,'Male':0})

#### question-1  Handling the Misssing value

In [47]:
df.isnull().sum()

RowNumber          0
CustomerId         0
CreditScore        0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
x=df.drop(columns=['Exited'])
y=df['Exited']

In [50]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [51]:
from sklearn.preprocessing import StandardScaler

In [52]:
sc=StandardScaler()

In [53]:
x_train_sc=sc.fit_transform(x_train)

In [54]:
x_train_new=pd.DataFrame(x_train_sc)

In [55]:
np.round(x_train_new.describe())

,0,1,2,3,4,5,6,7,8,9,10
count,8000.0,8000.0,8000.0,8000.0,8000.0,8000.0,8000.0,8000.0,8000.0,8000.0,8000.0
mean,-0.0,0.0,0.0,-0.0,-0.0,0.0,-0.0,0.0,-0.0,-0.0,0.0
std,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
min,-2.0,-2.0,-3.0,-1.0,-2.0,-2.0,-1.0,-1.0,-2.0,-1.0,-2.0
25%,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-2.0,-1.0,-1.0
50%,0.0,0.0,0.0,-1.0,-0.0,-0.0,0.0,-1.0,1.0,1.0,0.0
75%,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
max,2.0,2.0,2.0,1.0,5.0,2.0,3.0,4.0,1.0,1.0,2.0

# Attrition Dataset

In [56]:
df=pd.read_csv("C:\\Users\\HARSHITA\\Downloads\\New folder\\Attrition - Attrition.csv")
df.head(3)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0

In [57]:
categorical_col=df.select_dtypes(include=['object']).columns
categorical_col

Index(['Attrition', 'BusinessTravel', 'Department', 'EducationField', 'Gender',
       'JobRole', 'MaritalStatus', 'Over18', 'OverTime'],
      dtype='object')

In [58]:
df.drop(columns=['EducationField','JobRole','MaritalStatus','Over18','OverTime'],inplace=True)

In [59]:
numerical_col=df.select_dtypes(exclude=['object'])
numerical_col

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1102,1,2,1,1,2,94,3,2,...,1,80,0,8,0,1,6,4,0,5
1,49,279,8,1,1,2,3,61,2,2,...,4,80,1,10,3,3,10,7,1,7
2,37,1373,2,2,1,4,4,92,2,1,...,2,80,0,7,3,3,0,0,0,0
3,33,1392,3,4,1,5,4,56,3,1,...,3,80,0,8,3,3,8,7,3,0
4,27,591,2,1,1,7,1,40,3,1,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,884,23,2,1,2061,3,41,4,2,...,3,80,1,17,3,3,5,2,0,3
1466,39,613,6,1,1,2062,4,42,2,3,...,1,80,1,9,5,3,7,7,1,7
1467,27,155,4,3,1,2064,2,87,4,2,...,2,80,1,6,0,3,6,2,0,3
1468,49,1023,2,3,1,2065,4,63,2,2,...,4,80,0,17,3,2,9,6,0,8
1469,34,628,8,3,1,2068,2,82,4,2,...,1,80,0,6,3,4,4,3,1,2

In [60]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobSatisfaction             0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [61]:
df['Department']=df['Department'].map({'Sales':0,'Research':2,'Human Resource':1})

In [62]:
df['Attrition']=df['Attrition'].map({'No':0,'Yes':1})

In [63]:
df['BusinessTravel']=df['BusinessTravel'].map({'Travel_Rarely':0,'Travel_Frequently':1})

In [64]:
df['Gender']=df['Gender'].map({'Male':0,'Female':1})

In [65]:
x=df.drop(columns=['Attrition'])
y=df['Attrition']

In [66]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [67]:
sc=StandardScaler()

In [68]:
x_train_sc=sc.fit_transform(x_train)

In [69]:
x_train_new=pd.DataFrame(x_train_sc)

In [1]:
np.round(x_train_new.describe(),2)

NameError: name 'np' is not defined