# Standard Scaler

In [31]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [32]:
df=pd.read_csv("C:\\Users\\HARSHITA\\Downloads\\Data_sets\\housing.csv")
df.head(2)

   Avg. Area Income  ...                                            Address
0       79545.45857  ...  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...
1       79248.64245  ...  188 Johnson Views Suite 079\nLake Kathleen, CA...

[2 rows x 7 columns]

In [33]:
df=df.drop(columns='Address')

In [34]:
x=df.drop(columns=['Price'])
y=df['Price']

In [35]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [36]:
sc=StandardScaler()

In [37]:
x_train_sc=sc.fit_transform(x_train)

x_test_sc=sc.transform(x_test)

In [38]:
df_x_train=pd.DataFrame(x_train_sc,columns=x_train.columns)

In [39]:
df_x_test=pd.DataFrame(x_test_sc,columns=x_test.columns)

In [43]:
df_x_test

     Avg. Area Income  ...  Area Population
0           -0.623965  ...         0.775099
1           -1.067525  ...         0.738807
2            0.149955  ...        -0.690768
3            0.068295  ...        -1.168923
4            0.411630  ...         1.456940
..                ...  ...              ...
995          0.811163  ...        -1.365575
996          0.689652  ...         0.280399
997          1.161157  ...         0.939913
998          1.698325  ...         1.165858
999         -0.141458  ...        -0.402926

[1000 rows x 5 columns]

In [40]:
np.round(df_x_train.describe(),2)

       Avg. Area Income  ...  Area Population
count           4000.00  ...          4000.00
mean              -0.00  ...             0.00
std                1.00  ...             1.00
min               -4.75  ...            -3.60
25%               -0.67  ...            -0.68
50%                0.03  ...             0.01
75%                0.68  ...             0.67
max                3.37  ...             3.36

[8 rows x 5 columns]

# MinMax Scaler

In [41]:
from sklearn.preprocessing import MinMaxScaler

In [44]:
mn=MinMaxScaler()

In [45]:
x_train_mn=mn.fit_transform(x_train)

x_test_mn=mn.transform(x_test)

In [46]:
df_x_train=pd.DataFrame(x_train_mn,columns=x_train.columns)

df_x_test=pd.DataFrame(x_test_mn,columns=x_test.columns)

In [50]:
np.round(df_x_train.describe(),2)

       Avg. Area Income  ...  Area Population
count           4000.00  ...          4000.00
mean               0.58  ...             0.52
std                0.12  ...             0.14
min                0.00  ...             0.00
25%                0.50  ...             0.42
50%                0.59  ...             0.52
75%                0.67  ...             0.61
max                1.00  ...             1.00

[8 rows x 5 columns]