# KNN

In [77]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,classification_report
from sklearn.preprocessing import StandardScaler

In [78]:
df=pd.read_csv("C:\\Users\\HARSHITA\\OneDrive\\Documents\\Desktop\\Data_sets\\covid_toy - covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [79]:
df['fever']=df['fever'].fillna(df['fever'].mean())

In [80]:
le=LabelEncoder()

In [81]:
df['gender']=le.fit_transform(df['gender'])
df['cough']=le.fit_transform(df['cough'])
df['city']=le.fit_transform(df['city'])
df['has_covid']=le.fit_transform(df['has_covid'])

In [82]:
x=df.drop(columns=['has_covid'])
y=df['has_covid']

In [83]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [84]:
sc=StandardScaler()

In [85]:
x_train_sc=sc.fit_transform(x_train)
x_test_sc=sc.fit_transform(x_test)

In [86]:
knn=KNeighborsClassifier(n_neighbors=3)

In [87]:
knn.fit(x_train_sc,y_train)

KNeighborsClassifier(n_neighbors=3)

In [88]:
y_pred=knn.predict(x_test)

c:\Users\HARSHITA\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [89]:
accuracy_score(y_test,y_pred)

0.65

In [90]:
classification_report(y_test,y_pred)

c:\Users\HARSHITA\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\HARSHITA\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\HARSHITA\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

'              precision    recall  f1-score   support\n\n           0       0.65      1.00      0.79        13\n           1       0.00      0.00      0.00         7\n\n    accuracy                           0.65        20\n   macro avg       0.33      0.50      0.39        20\nweighted avg       0.42      0.65      0.51        20\n'

In [91]:
# Titanic dataset

In [92]:
df=pd.read_csv("C:\\Users\\HARSHITA\\OneDrive\\Documents\\Desktop\\Data_sets\\titanic - titanic.csv")
df.head(3)

   PassengerId  Survived  Pclass  ...    Fare Cabin  Embarked
0          892         0       3  ...  7.8292   NaN         Q
1          893         1       3  ...  7.0000   NaN         S
2          894         0       2  ...  9.6875   NaN         Q

[3 rows x 12 columns]

In [93]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [94]:
df=df.drop(columns=['Pclass','SibSp','Cabin','Fare'])

In [95]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [96]:
categorical_columns=df.select_dtypes(include=['object']).columns
categorical_columns

Index(['Name', 'Sex', 'Ticket', 'Embarked'], dtype='object')

In [97]:
df['Name']=le.fit_transform(df['Name'])
df['Sex']=le.fit_transform(df['Sex'])
df['Ticket']=le.fit_transform(df['Ticket'])
df['Embarked']=le.fit_transform(df['Embarked'])

In [98]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [99]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [100]:
x_train_sc=sc.fit_transform(x_train)
x_test_sc=sc.fit_transform(x_test)

In [101]:
knn.fit(x_train_sc,y_train)

KNeighborsClassifier(n_neighbors=3)

In [102]:
y_pred=knn.predict(x_test)

c:\Users\HARSHITA\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [103]:
accuracy_score(y_test,y_pred)

0.5952380952380952

In [104]:
# Chrun modelling

In [105]:
df=pd.read_csv("C:\\Users\\HARSHITA\\OneDrive\\Documents\\Desktop\\Data_sets\\Churn_Modelling - Churn_Modelling.csv")
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [106]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [107]:
categorical_columns=df.select_dtypes(include=['object']).columns
categorical_columns

Index(['Surname', 'Geography', 'Gender'], dtype='object')

In [108]:
df['Surname']=le.fit_transform(df['Surname'])
df['Geography']=le.fit_transform(df['Gender'])
df['Gender']=le.fit_transform(df['Geography'])

In [109]:
x=df.drop(columns=['Exited'])
y=df['Exited']

In [110]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [111]:
x_train_sc=sc.fit_transform(x_train)
x_test_sc=sc.fit_transform(x_test)

In [112]:
knn.fit(x_train_sc,y_train)

KNeighborsClassifier(n_neighbors=3)

In [113]:
y_pred=knn.predict(x_test)

c:\Users\HARSHITA\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

In [114]:
accuracy_score(y_test,y_pred)

0.7815