### DecisionTree Regressor

In [93]:
import pandas as pd
import numpy as np

In [94]:
df=pd.read_csv("C:\\Users\\HARSHITA\\Downloads\\Data_sets\\insurance - insurance.csv")
df.head(3)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [95]:
x=df.drop(columns=['charges'])
y=df['charges']

#### Encoding

In [96]:
from sklearn.preprocessing import LabelEncoder

In [97]:
le=LabelEncoder()

In [98]:
x['sex']=le.fit_transform(x['sex'])
x['smoker']=le.fit_transform(x['smoker'])
x['region']=le.fit_transform(x['region'])

#### Spliting Data

In [99]:
from sklearn.model_selection import train_test_split

In [100]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#### applying Model

In [101]:
from sklearn.tree import DecisionTreeRegressor

In [102]:
dt=DecisionTreeRegressor()

In [103]:
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [104]:
y_pred=dt.predict(x_test)

In [105]:
from sklearn.metrics import r2_score

In [106]:
r2_score(y_test,y_pred)

0.740784300101669

# DecisionTreeClassifier

In [107]:
df=pd.read_csv("C:\\Users\\HARSHITA\\Downloads\\Data_sets\\covid_toy - covid_toy.csv")
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [108]:
df['fever']=df['fever'].fillna(df['fever'].mean())

#### Encoding

In [109]:
le=LabelEncoder()

In [110]:
df['gender']=le.fit_transform(df['gender'])
df['cough']=le.fit_transform(df['cough'])
df['city']=le.fit_transform(df['city'])
df['has_covid']=le.fit_transform(df['has_covid'])

In [111]:
x=df.drop(columns=['has_covid'])
y=df['has_covid']

In [112]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [113]:
from sklearn.tree import DecisionTreeClassifier

In [114]:
dt=DecisionTreeClassifier()

In [115]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [116]:
y_pred=dt.predict(x_test)

In [117]:
from sklearn.metrics import accuracy_score

In [118]:
accuracy_score(y_test,y_pred)

0.45

## Churn-modelling

In [119]:
df=pd.read_csv("C:\\Users\\HARSHITA\\Downloads\\Data_sets\\Churn_Modelling - Churn_Modelling.csv")
df.head(2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [120]:
le=LabelEncoder()

In [121]:
df['Surname']=le.fit_transform(df['Surname'])
df['Geography']=le.fit_transform(df['Geography'])
df['Gender']=le.fit_transform(df['Gender'])

In [122]:
x=df.drop(columns=['Exited'])
y=df['Exited']

In [123]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#### Applying ML model

In [124]:
# from sklearn.tree import DecisionTreeClassifier

In [125]:
dt=DecisionTreeClassifier()

In [126]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [127]:
y_pred=dt.predict(x_test)

In [128]:
accuracy_score(y_test,y_pred)

0.7935

# Cars

In [129]:
df=pd.read_csv("C:\\Users\\HARSHITA\\Downloads\\Data_sets\\cars - cars.csv")
df.head(3)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC BSII,1992,50000,100000,Petrol,Individual,Manual,Fourth & Above Owner
1,Maruti Gypsy E MG410W ST,1995,95000,100000,Petrol,Individual,Manual,Second Owner
2,Mahindra Jeep CL 500 MDI,1996,250000,35000,Diesel,Individual,Manual,Second Owner

In [130]:
df['name']=le.fit_transform(df['name'])
df['fuel']=le.fit_transform(df['fuel'])
df['seller_type']=le.fit_transform(df['seller_type'])
df['transmission']=le.fit_transform(df['transmission'])
df['owner']=le.fit_transform(df['owner'])

In [131]:
x=df.drop(columns=['km_driven'])
y=df['km_driven']

In [132]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [133]:
dt=DecisionTreeRegressor()

In [134]:
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [135]:
y_pred=dt.predict(x_test)

In [136]:
r2_score(y_test,y_pred)

-0.3433397996818577