In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score,classification_report

In [4]:
df= pd.read_csv("C:\\Users\\HARSHITA\\Downloads\\archive (1)\\play_tennis.csv")
df.head(3)

  day   outlook temp humidity    wind play
0  D1     Sunny  Hot     High    Weak   No
1  D2     Sunny  Hot     High  Strong   No
2  D3  Overcast  Hot     High    Weak  Yes

In [5]:
# problem 

## outlook=Sunny temp=Hot and humidity=High wind=Weak
# play or not

In [ ]:
# solution

# p(yes|Sunny,Hot,High,Weak)=p(sunny|yes)*p(sunny|hot)*p(sunny|high)*p(sunny|weak)
# same for no

In [9]:
# during traning naive bayes will calculate all the probabilites in a dictionary

# than you give a test value  than it will look in lookup table

In [10]:
#lookup Tabel

In [11]:
#p(Yes)
#p(No)

In [13]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [ ]:
py=9/14
pn=5/14

In [16]:
# outlook
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [ ]:
pon=0
prn=2/5
psn=3/5

poy=4/9
pry=3/9
psy=2/9

In [17]:
# temp

pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [ ]:
pcoolNo=1/5
pHotNo=2/5
pMlidNo=2/5

pcoolYes=3/9
pHOtYes=2/9
pmildYes=4/9

In [18]:
# @ Humidity
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [ ]:
pHighNO=4/5
pHighYes=3/9

pnormalYes=6/9
pnornalno=

In [19]:
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [ ]:
pstrongyes=3/9
pstrongno=3/5
pweakyes=6/9
pweakno=2/5