In [67]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge,Lasso
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.metrics import accuracy_score

### Linear Regression

In [68]:
df=pd.read_csv("C:\\Users\\HARSHITA\\Downloads\\Data_sets\\insurance - insurance.csv")
df.head(3)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [69]:
x=df.drop(columns=['charges'])
y=df['charges']

#### Label Encoder

In [70]:
le=LabelEncoder()

In [71]:
x['sex']=le.fit_transform(x['sex'])
x['smoker']=le.fit_transform(x['smoker'])
x['region']=le.fit_transform(x['region'])

In [72]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [73]:
lr=LinearRegression()

In [74]:
lr.fit(x_train,y_train)

LinearRegression()

In [75]:
y_pred=lr.predict(x_test)

In [76]:
r2_score(y_test,y_pred)

0.7833463107364539

### Ridge

In [77]:
ridge=Ridge(alpha=0.5)
ridge.fit(x_train,y_train)

Ridge(alpha=0.5)

In [78]:
train_score_ridge=ridge.score(x_train,y_train)
test_score_ridge=ridge.score(x_test,y_test)
print("train_score_ridge",train_score_ridge)
print("test_score_ridge",test_score_ridge)

train_score_ridge 0.7416997372947685
test_score_ridge 0.7832200105774039

### Lasso

In [79]:
lasso=Lasso(alpha=0.2)
lasso.fit(x_train,y_train)

Lasso(alpha=0.2)

In [80]:
train_score_lasso=lasso.score(x_train,y_train)
test_score_lasso=lasso.score(x_test,y_test)
print("train_score_lasso",train_score_lasso)
print("test_score_lasso",test_score_lasso)

train_score_lasso 0.7417049248555514
test_score_lasso 0.7833410023117899

## Logistic Regression

In [81]:
df=pd.read_csv("C:\\Users\\HARSHITA\\Downloads\\Data_sets\\covid_toy - covid_toy.csv")
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [82]:
df['fever']=df['fever'].fillna(df['fever'].mean())

In [83]:
df['gender']=le.fit_transform(df['gender'])
df['cough']=le.fit_transform(df['cough'])
df['city']=le.fit_transform(df['city'])
df['has_covid']=le.fit_transform(df['has_covid'])

In [84]:
x=df.drop(columns=['has_covid'])
y=df['has_covid']

In [85]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [86]:
lr=LogisticRegression()

In [88]:
lr.fit(x_train,y_train)

LogisticRegression()

In [89]:
y_pred=lr.predict(x_test)

In [90]:
accuracy_score(y_test,y_pred)

0.75

### DecisionTreeClassifier

In [119]:
df=pd.read_csv("C:\\Users\\HARSHITA\\Downloads\\Data_sets\\covid_toy - covid_toy.csv")
df.head(2)
df['fever']=df['fever'].fillna(df['fever'].mean())

In [120]:
df['gender']=le.fit_transform(df['gender'])
df['cough']=le.fit_transform(df['cough'])
df['city']=le.fit_transform(df['city'])
df['has_covid']=le.fit_transform(df['has_covid'])

In [121]:
x=df.drop(columns=['has_covid'])
y=df['has_covid']

In [122]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [95]:
dt=DecisionTreeClassifier()

In [ ]:
dt.fit(x_train,y_train)

In [123]:
from sklearn.metrics import classification_report, roc_auc_score
def evaluate_model(true, predicted):
    score = accuracy_score(true, predicted)
    # report = classification_report(true, predicted)
    roc_auc = roc_auc_score(true, predicted)
    return score, roc_auc

In [124]:
models = {
    "Logistic Regression" : LogisticRegression(),
    "Decision Tree Classifier" : DecisionTreeClassifier(),
    "Random Forest Classifier" : RandomForestClassifier()
}

for model_name, model in models.items():
    model.fit(x_train, y_train)

    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)

    train_accuracy, train_roc_auc = evaluate_model(y_train, y_train_pred)
    test_accuracy, test_roc_auc = evaluate_model(y_test, y_test_pred)

    print(model_name)

    print("Model Performance for Training Set")
    print("- Accuracy: ", (train_accuracy))
    # print("- Classification Report: {:.4f}".format(train_report))
    print("- ROC AUC Score: ", (train_roc_auc))

    print("-" * 30)

    print("Model Performance for Test Data")
    print("- Accuracy: ", (test_accuracy))
    # print("- Classification Report: {:4f}".format(test_report))
    print("- ROC AUC Score: ", (test_roc_auc))

    print("=" * 30)

Logistic Regression
Model Performance for Training Set
- Accuracy:  0.625
- ROC AUC Score:  0.6215538847117795
------------------------------
Model Performance for Test Data
- Accuracy:  0.75
- ROC AUC Score:  0.7747252747252747
==============================
Decision Tree Classifier
Model Performance for Training Set
- Accuracy:  1.0
- ROC AUC Score:  1.0
------------------------------
Model Performance for Test Data
- Accuracy:  0.45
- ROC AUC Score:  0.478021978021978
==============================
Random Forest Classifier
Model Performance for Training Set
- Accuracy:  1.0
- ROC AUC Score:  1.0
------------------------------
Model Performance for Test Data
- Accuracy:  0.55
- ROC AUC Score:  0.6208791208791209
==============================

### RandomForestRegressor

In [107]:
df=pd.read_csv("C:\\Users\\HARSHITA\\Downloads\\Data_sets\\insurance - insurance.csv")
df.head(3)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [108]:
x=df.drop(columns=['charges'])
y=df['charges']

In [109]:
x['sex']=le.fit_transform(x['sex'])
x['smoker']=le.fit_transform(x['smoker'])
x['region']=le.fit_transform(x['region'])

In [110]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [111]:
rf=RandomForestRegressor()

In [112]:
rf.fit(x_train,y_train)

RandomForestRegressor()

In [113]:
y_pred=rf.predict(x_test)

In [114]:
r2_score(y_test,y_pred)

0.8642823713036882